### ISSUE TITLE
Can't find libcntsh.so

### ISSUE THREAD

**Issue by lameiro** [lameiro/cx_oracle_on_ctypes#15]
From @tkossak on https://github.com/lameiro/cx_oracle_on_ctypes/issues/14 :

Do you know why cx_oracle_on_ctypes can't find libclntsh.so library? Standard cx_Oracle can find it without me manually exporting LD_LIBRARY_PATH (because i have proper path set in /etc/ld.so.conf.d/oracle.conf), but somehow cx_oracle_on_ctypes ignores this path.

$ python -c 'import cx_Oracle'
$ export PYTHONPATH=/home/kossak/apps/cx_oracle_on_ctypes
$ python -c 'import cx_Oracle'
Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 2, in <module>
    from cx_Oracle.oci_generated_12 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 613, in <module>
    _libs["libclntsh.so.12.1"] = load_library("libclntsh.so.12.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_12.py", line 367, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.12.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 5, in <module>
    from cx_Oracle.oci_generated_11 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 596, in <module>
    _libs["libclntsh.so.11.1"] = load_library("libclntsh.so.11.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_11.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.11.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 8, in <module>
    from cx_Oracle.oci_generated_10 import *
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 596, in <module>
    _libs["libclntsh.so.10.1"] = load_library("libclntsh.so.10.1")
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci_generated_10.py", line 366, in load_library
    raise ImportError("%s not found." % libname)
ImportError: libclntsh.so.10.1 not found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/__init__.py", line 13, in <module>
    from cx_Oracle.connection import Connection
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/connection.py", line 4, in <module>
    from cx_Oracle import oci
  File "/home/kossak/apps/cx_oracle_on_ctypes/cx_Oracle/oci.py", line 10, in <module>
    raise Exception("Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.")
Exception: Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.
$ export LD_LIBRARY_PATH=/opt/oracle/oracle/product/12.1.0/client_1/lib
$ python -c 'import cx_Oracle'
$ echo $?
0

**Comment by lameiro** [comment]
Hi @tkossak,

I need a bit more information to reproduce this.

Which Linux distribution?
Are you pointing cx_oracle_on_ctypes to instant client libs or oracle server libs? Which version?
Could you send me the output of "ls -la" in the directory that contains libclntsh.so?
Also the contents of your /etc/ld.so.conf.d/oracle.conf ?

**Comment by tkossak** [comment]
I use:

- Linux Mint 18 x64 Cinnamon
- I have oracle instant client installed.
- cx_Oracle.clientversion() returns 12.1.0.2.0
- I created file `/etc/ld.so.conf.d/oracle.conf` containing one line:
`/opt/oracle/oracle/product/12.1.0/client_1/lib`
- Content of above folder:
```
total 424960
drwxr-xr-x  3 oracle oinstall    12288 May  6  2016 ./
drwxr-xr-x 45 oracle oinstall     4096 May  6  2016 ../
lrwxrwxrwx  1 oracle oinstall        4 May  4  2016 .1.0 -> .1.0
-rw-r--r--  1 oracle oinstall    64892 May 23  2014 acfslib.pm
-rw-r--r--  1 oracle oinstall    34936 May 23  2014 acfsroot.pl
-rwxr-xr-x  1 oracle oinstall     2965 May 23  2014 acfstoolsdriver.sh*
-rw-r--r--  1 oracle oinstall     3541 May 23  2014 afddriverstate.pl
-rw-r--r--  1 oracle oinstall     6887 May 23  2014 afdlib.pm
-rw-r--r--  1 oracle oinstall    14245 May 23  2014 afdroot.pl
-rwxr-xr-x  1 oracle oinstall     2802 May 23  2014 afdtoolsdriver.sh*
-rw-r--r--  1 oracle oinstall  1391056 May  4  2016 clntshcore.map
-rw-r--r--  1 oracle oinstall  4657291 May  4  2016 clntsh.map
-rw-r--r--  1 oracle oinstall     4114 May 23  2014 facility.lis
-rw-r--r--  1 oracle oinstall      115 May  4  2016 ldflags
-rw-r--r--  1 oracle oinstall      132 May  4  2016 ldflagsO
-rw-r--r--  1 oracle oinstall  1022104 Jul  1  2014 libacfs12.so
-rw-r--r--  1 oracle oinstall   272513 Jul  1  2014 libafd12.so
-rw-r--r--  1 oracle oinstall  1424630 Jul  7  2014 libagent12.a
-rw-r--r--  1 oracle oinstall 10376839 Jun 30  2014 libagfw12.so
lrwxrwxrwx  1 oracle oinstall       15 May  4  2016 libagtsh.so -> libagtsh.so.1.0
-rw-r--r--  1 oracle oinstall  2530064 Jul  7  2014 libagtsh.so.1.0
-rw-r--r--  1 oracle oinstall  1962032 Jul  7  2014 libasmclnt12.a
-rw-r--r--  1 oracle oinstall  2187792 Jul  7  2014 libasmclntsh12.a
-rw-r--r--  1 oracle oinstall  1670948 Jul  7  2014 libasmclntsh12.so
-rw-r--r--  1 oracle oinstall   415660 Jan  2  2014 libccme_asym.so
-rw-r--r--  1 oracle oinstall   306612 May  6  2014 libccme_base_non_fips.so
-rw-r--r--  1 oracle oinstall   555820 Jan  2  2014 libccme_base.so
-rw-r--r--  1 oracle oinstall   812074 Nov 14  2013 libccme_ecc_accel_fips.so
-rw-r--r--  1 oracle oinstall   780387 May  6  2014 libccme_ecc_accel_non_fips.so
-rw-r--r--  1 oracle oinstall   461494 May  6  2014 libccme_ecc_non_fips.so
-rw-r--r--  1 oracle oinstall   709631 Jan  2  2014 libccme_ecc.so
-rw-r--r--  1 oracle oinstall  6791124 Jul  7  2014 libcell12.so
-rw-r--r--  1 oracle oinstall 11237440 Jul  7  2014 libclient12.a
lrwxrwxrwx  1 oracle oinstall       68 May  4  2016 libclntshcore.so -> /opt/oracle/oracle/product/12.1.0/client_1/lib/libclntshcore.so.12.1*
-rwxr-xr-x  1 oracle oinstall  6994667 May  4  2016 libclntshcore.so.12.1*
lrwxrwxrwx  1 oracle oinstall       64 May  4  2016 libclntsh.so -> /opt/oracle/oracle/product/12.1.0/client_1/lib/libclntsh.so.12.1*
lrwxrwxrwx  1 oracle oinstall       12 May  4  2016 libclntsh.so.10.1 -> libclntsh.so*
lrwxrwxrwx  1 oracle oinstall       12 May  4  2016 libclntsh.so.11.1 -> libclntsh.so*
-rwxr-xr-x  1 oracle oinstall 58795628 May  4  2016 libclntsh.so.12.1*
-rw-r--r--  1 oracle oinstall        0 Jul  7  2014 libclntst12.a
-rw-r--r--  1 oracle oinstall   632149 Jun 30  2014 libclsce12.so
-rw-r--r--  1 oracle oinstall   462362 Jun 30  2014 libclsra12.so
-rw-r--r--  1 oracle oinstall 10085432 Jul  7  2014 libcommon12.a
-rw-r--r--  1 oracle oinstall  5803698 Jun 17  2014 libcore12.a
-rw-r--r--  1 oracle oinstall  2574084 Jun 17  2014 libcorejava.so
-rw-r--r--  1 oracle oinstall     2638 Jan  2  2014 libcryptocme.sig
-rw-r--r--  1 oracle oinstall   445946 Jan  2  2014 libcryptocme.so
-rw-r--r--  1 oracle oinstall     5612 May 23  2014 libcxaguard.so.5
-rw-r--r--  1 oracle oinstall   196409 Jun 30  2014 libdbcfg12.so
-rw-r--r--  1 oracle oinstall   196447 Jun 30  2014 libeons.so
-rw-------  1 oracle oinstall   617772 Nov  8  2011 libexpat.a
-rw-------  1 oracle oinstall      793 Nov  8  2011 libexpat.la
-rw-------  1 oracle oinstall   408282 Nov  8  2011 libexpat.so
-rw-------  1 oracle oinstall   408282 Nov  8  2011 libexpat.so.1
-rw-------  1 oracle oinstall   408282 Nov  8  2011 libexpat.so.1.5.2
-rw-r--r--  1 oracle oinstall 34491692 Jul  7  2014 libgeneric12.a
-rw-r--r--  1 oracle oinstall  1969487 Jun 30  2014 libgns12.so
-rw-r--r--  1 oracle oinstall   346309 Jun 30  2014 libgnsjni12.so
-rw-r--r--  1 oracle oinstall 26442803 Jun 30  2014 libhasgen12.so
-rw-r--r--  1 oracle oinstall    18027 Jun 30  2014 libheteroxa12.so
-rw-r--r--  1 oracle oinstall  4899672 May 23  2014 libimf.a
-rw-r--r--  1 oracle oinstall   352351 May 23  2014 libintlc.so.5
-rw-r--r--  1 oracle oinstall  2457778 Jun 18  2014 libipc1.a
-rw-r--r--  1 oracle oinstall  1768370 Jun 18  2014 libipc1.so
-rw-r--r--  1 oracle oinstall   116302 Dec  3  2013 libipp_bz2.a
-rw-r--r--  1 oracle oinstall   103952 Dec  3  2013 libippcore.a
-rw-r--r--  1 oracle oinstall  1342006 Jul  7  2014 libippcpemerged.a
-rw-r--r--  1 oracle oinstall 10651828 Jul  7  2014 libippcpmerged.a
-rw-r--r--  1 oracle oinstall   339570 Dec  3  2013 libippdcemerged.a
-rw-r--r--  1 oracle oinstall  2652644 Dec  3  2013 libippdcmerged.a
-rw-r--r--  1 oracle oinstall  4971338 Dec  3  2013 libippsemerged.a
-rw-r--r--  1 oracle oinstall 47924222 Dec  3  2013 libippsmerged.a
-rw-r--r--  1 oracle oinstall   129660 Dec  3  2013 libipp_z.a
-rw-r--r--  1 oracle oinstall   534212 May 23  2014 libirc.a
-rw-r--r--  1 oracle oinstall  1656964 Jun 18  2014 libldapclnt12.a
-rw-r--r--  1 oracle oinstall    44498 Jun 18  2014 libldapjclnt12.a
-rw-r--r--  1 oracle oinstall    75510 Jun 18  2014 libldapjclnt12.so
-rw-r--r--  1 oracle oinstall   120118 Jun 19  2014 liblxled.a
-rw-r--r--  1 oracle oinstall   889598 Jun 17  2014 liblzopro.a
-rw-r--r--  1 oracle oinstall     6020 Jul  7  2014 libmm.a
-rw-r--r--  1 oracle oinstall   666598 Jun 18  2014 libmql1.a
-rw-r--r--  1 oracle oinstall   544150 Jun 18  2014 libmql1.so
-rw-r--r--  1 oracle oinstall  9169174 May  4  2016 libn12.a
-rw-r--r--  1 oracle oinstall   113496 Jun 27  2014 libnbeq12.a
-rw-r--r--  1 oracle oinstall   197030 Jun 26  2014 libncrypt12.a
-rw-r--r--  1 oracle oinstall    96003 Jul  7  2014 libnfsodm12.so
-rw-r--r--  1 oracle oinstall    29204 Jun 27  2014 libnhost12.a
-rw-r--r--  1 oracle oinstall   195875 Jun 27  2014 libnjni12.so
-rw-r--r--  1 oracle oinstall  1540260 Jun 27  2014 libnl12.a
-rw-r--r--  1 oracle oinstall   329216 Jun 27  2014 libnldap12.a
-rw-r--r--  1 oracle oinstall  2919180 Jun 19  2014 libnls12.a
-rw-r--r--  1 oracle oinstall    24574 Jul  7  2014 libnnet12.a
-rw-r--r--  1 oracle oinstall    24574 Jul  7  2014 libnnetd12.a
-rw-r--r--  1 oracle oinstall  1753146 Jun 18  2014 libnnz12.a
-rw-r--r--  1 oracle oinstall  6213011 Jun 18  2014 libnnz12.so
-rw-r--r--  1 oracle oinstall 20829764 Jun 18  2014 libnnzst12.a
-rw-r--r--  1 oracle oinstall    13162 Jun 27  2014 libnoname12.a
-rw-r--r--  1 oracle oinstall    89737 Jun 27  2014 libnque12.so
-rw-r--r--  1 oracle oinstall  1022726 Jun 27  2014 libnro12.a
-rw-r--r--  1 oracle oinstall   217540 Jun 27  2014 libnsgr12.a
-rw-r--r--  1 oracle oinstall   277530 Jun 27  2014 libntcp12.a
-rw-r--r--  1 oracle oinstall    13594 Jun 27  2014 libntcpaio12.so
-rw-r--r--  1 oracle oinstall   307394 Jun 27  2014 libntcps12.a
-rw-r--r--  1 oracle oinstall   124448 Jun 27  2014 libntmq12.a
-rw-r--r--  1 oracle oinstall    40130 Jun 27  2014 libntns12.a
-rw-r--r--  1 oracle oinstall   155584 Jun 27  2014 libnus12.a
-rw-r--r--  1 oracle oinstall     9958 Jun 27  2014 libnzjs12.a
-rw-r--r--  1 oracle oinstall  5088996 Jul  7  2014 libocci12.a
lrwxrwxrwx  1 oracle oinstall       15 May  4  2016 libocci.so -> libocci.so.12.1*
-rwxr-xr-x  1 oracle oinstall  2578997 May  4  2016 libocci.so.12.1*
-rw-r--r--  1 oracle oinstall   156353 Jun 30  2014 libocijdbc12.so
-rw-r--r--  1 oracle oinstall  4059920 Jun 30  2014 libocr12.so
-rw-r--r--  1 oracle oinstall  7843305 Jun 30  2014 libocrb12.so
-rw-r--r--  1 oracle oinstall   569688 Jun 30  2014 libocrutl12.so
-rw-r--r--  1 oracle oinstall    10170 Jul  7  2014 libodm12.a
-rw-r--r--  1 oracle oinstall    14605 Jul  7  2014 libodmd12.so
-rw-r--r--  1 oracle oinstall   868860 Jun 30  2014 liboevm.a
-rw-r--r--  1 oracle oinstall   337137 Jun 18  2014 libons.so
-rw-r--r--  1 oracle oinstall   117106 Jun 17  2014 liborabz2.a
-rw-r--r--  1 oracle oinstall   135326 Jul  7  2014 liboramysql12.a
-rw-r--r--  1 oracle oinstall   118491 Jul  7  2014 liboramysql12.so
-rw-r--r--  1 oracle oinstall   164452 Jun 17  2014 liboraz.a
-rw-r--r--  1 oracle oinstall   137752 Jul  7  2014 liborion12.a
-rw-r--r--  1 oracle oinstall    91568 Jun 18  2014 libowm2.so
-rw-r--r--  1 oracle oinstall   235076 Jul  7  2014 libplc12.a
-rw-r--r--  1 oracle oinstall   242108 Jul  7  2014 libplc12_pic.a
-rw-r--r--  1 oracle oinstall  5262112 Jul  7  2014 libplp12.a
-rw-r--r--  1 oracle oinstall  5319952 Jul  7  2014 libplp12_pic.a
-rw-r--r--  1 oracle oinstall 13965424 Jul  7  2014 libpls12.a
-rw-r--r--  1 oracle oinstall 13796608 Jul  7  2014 libpls12_pic.a
-rw-r--r--  1 oracle oinstall   389414 Jul  7  2014 libpsa12.a
-rw-r--r--  1 oracle oinstall   203424 Jun 30  2014 librdjni12.so
-rw-r--r--  1 oracle oinstall    13906 Jul  7  2014 libskgxn2.so
-rw-r--r--  1 oracle oinstall  1135218 Jul  7  2014 libskgxp12.so
-rw-r--r--  1 oracle oinstall    24795 Jul  7  2014 libskgxpcompat.so
-rw-r--r--  1 oracle oinstall    24795 Jul  7  2014 libskgxpd.so
-rw-r--r--  1 oracle oinstall  1135218 Jul  7  2014 libskgxpg.so
-rw-r--r--  1 oracle oinstall  1135248 Jul  7  2014 libskgxpr.so
-rw-r--r--  1 oracle oinstall    25676 Jun 18  2014 libslax12.a
-rw-r--r--  1 oracle oinstall   356272 Jun 19  2014 libsnls12.a
-rw-r--r--  1 oracle oinstall  1188964 Jul  7  2014 libsql12.a
-rw-r--r--  1 oracle oinstall  2234110 Jun 18  2014 libsqlplus.a
-rw-r--r--  1 oracle oinstall  1546540 Jun 18  2014 libsqlplus.so
-rw-r--r--  1 oracle oinstall   181808 Jun 30  2014 libsrvm12.so
-rw-r--r--  1 oracle oinstall    35515 Jun 30  2014 libsrvmcred12.so
-rw-r--r--  1 oracle oinstall  1875506 Jun 30  2014 libsrvmhas12.so
-rw-r--r--  1 oracle oinstall    96029 Jun 30  2014 libsrvmocr12.so
-rw-r--r--  1 oracle oinstall 10514442 May 23  2014 libsvml.a
-rw-r--r--  1 oracle oinstall    83062 Jun 30  2014 libuini12.so
-rw-r--r--  1 oracle oinstall   265906 Jun 19  2014 libunls12.a
-rw-r--r--  1 oracle oinstall    10030 Jul  7  2014 libvsn12.a
-rw-r--r--  1 oracle oinstall    10078 Jul  7  2014 libvsn12_cee.a.dbl
-rw-r--r--  1 oracle oinstall    10070 Jul  7  2014 libvsn12_cse.a.dbl
-rw-r--r--  1 oracle oinstall    10046 Jul  7  2014 libvsn12_std.a.dbl
-rw-r--r--  1 oracle oinstall   358124 Jan 31  2013 libwwg.a
-rw-r--r--  1 oracle oinstall   406094 Jul  7  2014 libxdb.so
-rw-r--r--  1 oracle oinstall 11448910 Jun 27  2014 libxml12.a
-rw-r--r--  1 oracle oinstall   192038 Jun 18  2014 libzt12.a
-rw-r--r--  1 oracle oinstall  4454684 Jun 18  2014 libztkg12.a
-rw-r--r--  1 oracle oinstall    10256 Jun 27  2014 naect.o
-rw-r--r--  1 oracle oinstall     5576 Jun 27  2014 naedhs.o
-rw-r--r--  1 oracle oinstall    16416 Jun 27  2014 naeet.o
-rw-r--r--  1 oracle oinstall     5784 Jun 26  2014 nautab.o
-rw-r--r--  1 oracle oinstall    18952 Jun 27  2014 nigcon.o
-rw-r--r--  1 oracle oinstall     5984 Jun 27  2014 nigtab.o
-rw-r--r--  1 oracle oinstall     1968 May  4  2016 nnfgt.o
-rw-r--r--  1 oracle oinstall     2512 May  4  2016 ntcontab.o
-rw-r--r--  1 oracle oinstall    19734 Jun  6  2014 okalib.pm
-rw-r--r--  1 oracle oinstall    22457 Jun  6  2014 okaroot.pl
-rwxr-xr-x  1 oracle oinstall     2820 May 23  2014 okatoolsdriver.sh*
-rw-r--r--  1 oracle oinstall    49698 May 23  2014 osds_acfslib.pm
-rw-r--r--  1 oracle oinstall    47367 May 23  2014 osds_acfsroot.pm
-rw-r--r--  1 oracle oinstall     2818 May 23  2014 osds_afddriverstate.pm
-rw-r--r--  1 oracle oinstall     7908 May 23  2014 osds_afdlib.pm
-rw-r--r--  1 oracle oinstall    25960 May 23  2014 osds_afdroot.pm
-rw-r--r--  1 oracle oinstall     5000 May 23  2014 osds_okalib.pm
-rw-r--r--  1 oracle oinstall    22606 May 23  2014 osds_okaroot.pm
-rw-r--r--  1 oracle oinstall    28427 May 23  2014 osds_unix_linux_acfslib.pm
-rw-r--r--  1 oracle oinstall     6740 May 23  2014 osds_unix_linux_afdlib.pm
-rw-r--r--  1 oracle oinstall     3086 May 23  2014 osds_unix_linux_okalib.pm
-rw-r--r--  1 oracle oinstall     6056 Jun 27  2014 osntabst.o
-rw-r--r--  1 oracle oinstall     6016 Jun 17  2014 s0main.o
-rw-r--r--  1 oracle oinstall     3408 Jun 17  2014 scorept.o
-rw-r--r--  1 oracle oinstall     3120 Jun 17  2014 sscoreed.o
drwxr-xr-x  2 oracle oinstall     4096 May  4  2016 stubs/
-rw-r--r--  1 oracle oinstall       55 May 23  2014 sysliblist
-rw-r--r--  1 oracle oinstall    12112 Jun 27  2014 xmlcomp2.jar
-rw-r--r--  1 oracle oinstall   596274 Jun 27  2014 xml.jar
-rw-r--r--  1 oracle oinstall   679842 Jun 27  2014 xmlmesg.jar
-rw-r--r--  1 oracle oinstall  1669142 Jun 27  2014 xmlparserv2.jar
-rw-r--r--  1 oracle oinstall     1816 Jun 27  2014 xmlparserv2_jaxp_services.jar
-rw-r--r--  1 oracle oinstall  1666571 Jun 27  2014 xmlparserv2_sans_jaxp_services.jar
-rw-r--r--  1 oracle oinstall   161690 Jun 27  2014 xschema.jar
-rw-r--r--  1 oracle oinstall   203755 Jun 27  2014 xsu12.jar
```

**Comment by kakash1hatake** [comment]
On python 3.7 I also have such an error

> Could not import oracle libraries version 12, 11 or 10. Giving up. Don't forget to set your ORACLE_HOME and LD_LIBRARY_PATH.

but it is because the real error is not shown. 
And if we add more info to the exception reraise instruction it shows that module oci_generated_12 is not known(actually all version modules are not found at runtime).
It's all because of poor coding that is not compatible with modern versions of python.
I'm going to try to adopt it and it I succeed then I'm going to publish it on GitHub.
