### ISSUE TITLE
cx_Oracle is not importing in python after successful installation of cx_Oracle.please help me to solve the issue

### ISSUE THREAD

**Issue by ravi7893** [lameiro/cx_oracle_on_ctypes#19]
python version - 3.7.5rc1(64bit)
windows 10 64 bit
pip version - 19.3.1
pip install cx_Oracle
Requirement already satisfied: cx_Oracle in c:\python\lib\site-packages (7.2.3)
now in python terminal:

 import cx_Oracle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\rames\AppData\Roaming\Python\Python37\site-packages\cx_Oracle\__init__.py", line 10, in <module>
    from custom_exceptions import Warning, Error, InterfaceError, DatabaseError, DataError, OperationalError, IntegrityError, InternalError, ProgrammingError, NotSupportedError
ModuleNotFoundError: No module named 'custom_exceptions'

**Comment by kakash1hatake** [comment]
Hi. I had also such issue with python 3.7 on linux too.
The solution is to set environment variables correctly especially PYTHONPATH which tells where python search its modules.
But the bigger problem is that code that is installed via pip3 is not compatible with python 3 version
