### ISSUE TITLE
ReplaceArgtypeByVoidPointerContextManager is not thread-safe

### ISSUE THREAD

**Issue by K0Te** [lameiro/cx_oracle_on_ctypes#8]
Hi,

Context manager utils.ReplaceArgtypeByVoidPointerContextManager can fail to restore initial oci function arguments in multi-threaded application.
Issue can be reproduced with following script(once in ~5 runs on my machine):
```
import cx_Oracle
from threading import Thread
CNT = 40

class TSelector(Thread):
    def run(self):
        con = cx_Oracle.connect('test/test@TDB')
        cur = cur_acc = con.cursor()
        cur.execute('SELECT 1 FROM DUAL')
        for row in cur:
            print('Thread: %s Got row: %s' % (id(self), row,))
        cur.close()
        con.close()

threads = [TSelector() for _ in range(CNT)]
[t.start() for t in threads]
[t.join() for t in threads]

``` 

Here is example output:
```
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib64/pypy-2.6.1/lib-python/2.7/threading.py", line 806, in __bootstrap_inner
    self.run()
  File "t.py", line 7, in run
    con = cx_Oracle.connect('test/test@TDB')
  File "/home/porta-one/cx_Oracle/connection.py", line 42, in __init__
    self.environment = Environment.new_from_scratch(threaded, events, encoding, nencoding)
  File "/home/porta-one/cx_Oracle/environment.py", line 46, in new_from_scratch
    env = Environment(handle)
  File "/home/porta-one/cx_Oracle/environment.py", line 25, in __init__
    status = oci.OCIHandleAlloc(handle, byref(error_handle_as_void_p), oci.OCI_HTYPE_ERROR, 0, argtypes[4]())
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 714, in __call__
    funcptr = self._getfuncptr(argtypes, restype, thisarg)
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 421, in _getfuncptr
    ptr = self._getfuncptr_fromaddress(argtypes, restype)
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 410, in _getfuncptr_fromaddress
    ffiargs = [argtype.get_ffi_argtype() for argtype in argtypes]
AttributeError: 'AnythingGoes' object has no attribute 'get_ffi_argtype'
```
One more:
```
  File "/usr/lib64/pypy-2.6.1/lib-python/2.7/threading.py", line 806, in __bootstrap_inner
    self.run()
  File "t.py", line 7, in run
    con = cx_Oracle.connect('test/test@TDB')
  File "/usr/lib64/pypy-2.6.1/site-packages/cx_Oracle/connection.py", line 61, in __init__
    self.connect(mode, twophase, newpassword)
  File "/usr/lib64/pypy-2.6.1/site-packages/cx_Oracle/connection.py", line 69, in connect
    OCIHandleAlloc(self.environment, self.server_handle, oci.OCI_HTYPE_SERVER, "Connection_Connect(): allocate server handle")
  File "/usr/lib64/pypy-2.6.1/site-packages/cx_Oracle/pythonic_oci.py", line 31, in OCIHandleAlloc
    status = oci.OCIHandleAlloc(environment.handle, byref(handle), handle_type, 0, argtypes[4]())
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 720, in __call__
    return CFuncPtr.__call__(self, *args)
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 350, in __call__
    self._convert_args(argtypes, args, kwargs))
  File "/usr/lib64/pypy-2.6.1/lib_pypy/_ctypes/function.py", line 579, in _convert_args
    raise ArgumentError(str(e))
ArgumentError: expected LP_c_void_p instance instead of LP_LP_struct_OCIServer
```

**Comment by K0Te** [comment]
Here is pull request with fix:
https://github.com/lameiro/cx_oracle_on_ctypes/pull/9

**Comment by lameiro** [comment]
Hi K0Te, thanks once again for finding the problem, for the excellent reproduction script and for the fix. I decided to fix it in a slightly different way, by eliminating that context manager and adapting the callers. Anyway, your input was extremely useful. 

I will close the PR and the issue but let me know if you still have problems.
